---
title: "PUBPOL543-Final-MenghanZhai"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---
    
Row
-------------------------------------

### Plot1: univariate - Frequency Table of Race in the United States

```{r}
#upload ACS data
library(foreign)
link = "https://github.com/G7-PUBPOL-543/ACS/raw/main/ManipulatedACS_V2.dta"
ACSData = read.dta(link)

# check variable: race
# Check names of all the variables in ACS Data
#names(ACSData)


#see values in the variable race:
#head(ACSData$race,20)


# get frequency table of race: RaceFreq
# absolute values
RaceCount = table(ACSData$race,
                  exclude = 'nothing') 
#RaceCount


# relative values
RaceProptoplot = prop.table(RaceCount)*100
#RaceProptoplot


# Turn the frequency table into a data frame:
RaceFreq = as.data.frame(RaceProptoplot)


# renaming data frame
names(RaceFreq) = c("race","pct")

#RaceFreq


#Time to plot!
library(ggplot2)
# Order RaceFreq
RaceFreq = RaceFreq[order(RaceFreq$pct),]
#RaceFreq
# save the order
RaceOrd = RaceFreq[order(RaceFreq$pct),'race']


#base
base = ggplot(data = RaceFreq, 
             aes(x = race,
                 y = pct)) 
base = base + theme_light() # add background: light theme
## add order
base = base + scale_x_discrete(limits=RaceOrd) 
#base


# plot1: + geom bar
plot1 = base + geom_bar(stat='identity')
#plot1


# plot2: + title
# name the title
TitleRace = list(Title = "Frequency Table of Race in the United States",
                 SubTi = NULL,
                 XTi = "Race",
                 YTi = "Percentage",
                 Sou = "Source: 2019 American Community Survey (ACS) Data")
# add title
plot2 = plot1 + labs(title = TitleRace$Title,
                    subtitle = TitleRace$SubTi,
                    x = TitleRace$XTi,
                    y = TitleRace$YTi,
                    caption = TitleRace$Sou)
#plot2


# plot3: customize Y axis
library(scales)
plot3 = plot2 + scale_y_continuous(breaks = c(5, 10, 20, 40, 60, 80),
                                   limits = c(0, 80),
                                   labels = unit_format(suffix = '%')) 
#plot3


# plot4: Title/subtitle positions:
plot4 = plot3 + theme(plot.caption = element_text(hjust = 1),
                      plot.title = element_text(hjust = 0.5))
plot4 = plot4 + coord_flip() # flip the plot to fully show the types of race
#plot4


# plot5: Annotating the bars:
# paste0(round(RaceFreq$pct,2), '%')
LABELS = paste0(round(RaceFreq$pct,2), '%')
plot5 = plot4 + geom_text(vjust = 0,
                          hjust = -0.1,
                          size = 3,
                          aes(y = pct ,
                              label = LABELS))

# Final Univariate Plot
plot5
```


### Plot2: bivariate - Contingency Tables of Race and Health Insurance Coverage in the United States

```{r}
# I'll explore Race and Health Insurance Coverage in the United States in this plot.
# As these two variable are both categorical, I'll use contigency tables to organize the relationship.

#head(ACSData,5)


# check variable hcovany: with health insurance coverage or not
#head(ACSData$hcovany,20)


# contingency table of counts
RaceHIC = table(ACSData$race,ACSData$hcovany) # race and health insurance coverage


# compute marginal percent (per column) from contingency table
library(magrittr)
RaceHIC_mgCol = prop.table(RaceHIC,
                           margin = 2)%>%round(.,3)


# make a data frame from contingency table
RaceHIC_DF = as.data.frame(RaceHIC)
names(RaceHIC_DF) = c("race","HICstatus","counts")
#RaceHIC_DF


#adding marginal percents:
RaceHIC_DF$pctCol = as.data.frame(RaceHIC_mgCol)[,3]
#RaceHIC_DF


# try contingency table
# plot a representation of contingency table:
library(ggplot2)                           
base3 = ggplot(RaceHIC_DF, aes(x = HICstatus,y = counts)) 
tablePlot = base3 + geom_point(aes(size = pctCol*100)) 
tablePlot = tablePlot + geom_text(aes(label = percent(pctCol)),
                                  nudge_x = 0.15,
                                  size = 3)
#tablePlot


# improve the previous plot
tablePlot = tablePlot + theme_minimal()
tablePlot = tablePlot + theme(legend.position = "none")

#tablePlot


# barplot with less information
base4 = ggplot(RaceHIC_DF, aes(x = race, y = counts)) 

# bars
bars = base4 + geom_bar(stat = "identity") + theme_minimal()

# bar per health insurance status with 'facet'
barsFa = bars + facet_grid(~ HICstatus) 
#barsFa


# improve previous plot
# change the minimal theme
barsFa = barsFa + theme(axis.text.x = element_text(angle = 90,
                                                   hjust = 1,
                                                   size = 7))
#barsFa


# original relationship Input-Output table
base5  = ggplot(RaceHIC_DF, aes(x = race,  y = pctCol ) ) 
barsIO = base5 + geom_bar(stat = "identity")
barsIO = barsIO + facet_grid( ~ HICstatus) 
barsIO = barsIO + coord_flip()
#barsIO


# introduce "reorder""

# race ordered by pctcol
base5b  = ggplot(RaceHIC_DF, 
                 aes(x = reorder(race, pctCol),
                     y = pctCol) ) 

barsIOb = base5b + geom_bar(stat = "identity")
barsIOb = barsIOb + facet_grid( ~ HICstatus) 
barsIOb = barsIOb + coord_flip() 

barsIOb = barsIOb + theme(axis.text.y = element_text(size = 7,angle = 45)) 
#barsIOb


# Nice try. Next step is to:
# add titles
# name the title
TitleRaHI = list(Title = " Health Insurance Coverage Status by Race in the U.S.",
                 SubTi = NULL,
                 XTi = "Race",
                 YTi = "Percentage, Health Insurance Coverage Status",
                 Sou = "Source: 2019 American Community Survey (ACS) Data")
# add title
barsIObTi = barsIOb + labs(title = TitleRaHI$Title,
                           subtitle = TitleRaHI$SubTi,
                           x = TitleRaHI$XTi,
                           y = TitleRaHI$YTi,
                           caption = TitleRaHI$Sou)
#barsIObTi
# title positions
barsIObTi1 = barsIObTi + theme(plot.caption = element_text(hjust = 1),
                               plot.title = element_text(hjust = 0.5))


# Final Bivariable Plot
barsIObTi1

# That's all for my final project. Thank you!!
```

### Map: Visualization of Poverty Rate by State in the United States

```{r}
# head(ACSData$poverty,40)

# generate a new povertyst variable to show if one is in poverty. According to IPUM.USA, poverty < 100 represents "in poverty" status, and poverty>=100 is regarded as "not in poverty".
ACSData$povertyst 
ACSData$povertyst <- (ACSData$poverty < 100) # if poverty<100, then povertyst=TRUE, povertyst_num=1

ACSData$povertyst_num <- as.numeric(ACSData$povertyst) # generate a numeric variable to calculate poverty rate by state
#head(ACSData$povertyst_num,20)

#head(ACSData,5) #check

library(dplyr)
ACSData1 <- data.frame(ACSData$statefip , ACSData$povertyst_num) # Create a new data frame
#head(ACSData1,5)

# calculate the percent of "in poverty" of each state
# generate "count" variable to count for the total number of person of each state
ACSData1$count 
ACSData1$count <- 1
#head(ACSData1,5)


# calculate
library(dplyr)
ACSData2 <- group_by(ACSData1, ACSData.statefip) %>%
  mutate(percent = sum(ACSData.povertyst_num)/sum(count))
#head(ACSData2,5)


# save the "percent" to new dataframe
ACSData3 <- ACSData2 %>%
  distinct(ACSData.statefip, percent, .keep_all = TRUE)

#head(ACSData3,5)

# generate a new "NAME" variable  in ACSData3 which equals the original statefip in ACS data to merge the data and the map.
ACSData3$NAME = ACSData3$ACSData.statefip

#head(ACSData3,5)


# capitalize NAME in ACSData3 so that it is the same as NAME in map
ACSData4 = as.data.frame(ACSData3) # change it to a data frame
#head(ACSData4,5)

ACSData4$NAME_char <- as.character(ACSData4$NAME) # Apply as.character function
#head(ACSData4$NAME_char,5)

library(Hmisc)
ACSData4$NAME_char = capitalize(ACSData4$NAME_char)
#head(ACSData4,5)

ACSData4$NAME <- as.factor(ACSData4$NAME_char) 
#head(ACSData4,5)

# new column "poverty_rate" with the right name to show in map
ACSData4$poverty_rate = ACSData4$percent 
#head(ACSData4,5)


# open the map
linkMap = "https://github.com/G7-PUBPOL-543/maps/raw/main/states.geojson"
library(sf)
mapUS = read_sf(linkMap)


# see data in map
#head(mapUS)
#str(ACSData4)


# Merge ACS data and U.S. map by state name
mapUSVars = merge(mapUS,
                  ACSData4, 
                  by='NAME') 

#mapUSVars


# 1.Base layer: Map of U.S.
library(ggplot2)
# plot original map
base = ggplot(data = mapUS) + geom_sf(fill = 'grey90',
                                      color = NA) + theme_classic()
#base #base map of the U.S.


# 2.Data layer: Poverty Rate Map by State in the United States
povMap = base + geom_sf(data = mapUSVars,
                        aes(fill = poverty_rate),
                        color = NA)
#povMap


# change color
povMap1 = povMap + scale_fill_gradient(low = 'blue',
                                       high= 'yellow')


# add titles
# name the title
TitlePovMap = list(Title = " Poverty Rate Map by State in the United States",
                   SubTi = NULL,
                   XTi = NULL,
                   YTi = NULL,
                   Sou = "Source: 2019 American Community Survey (ACS) Data")

# add title
povMap2 = povMap1 + labs(title = TitlePovMap$Title,
                    subtitle = TitlePovMap$SubTi,
                    x = TitlePovMap$XTi,
                    y = TitlePovMap$YTi,
                    caption = TitlePovMap$Sou)
# povMap2
# title positions
povMap3 = povMap2 + theme(plot.caption = element_text(hjust = 1),
                          plot.title = element_text(hjust = 0.5))


# Final Map
povMap3
```





