---
title: "Kalyssa's Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(sf)
library(ggplot2)
location="https://github.com/G7-PUBPOL-543/wa-school-data/raw/main/2019%20Report_DistrictTotals.csv"
schools=read.csv(location)
```

Row
-----------------------------------------------------------------------

### Univariate Plot

```{r}
Gender=schools[,c('Female','Male','Gender.X')]
# column totals


genderFrequency=as.data.frame(colSums(Gender))

names(genderFrequency)=c('count')


genderFrequency$gender=rownames(genderFrequency)



library(ggplot2)
base=ggplot(data=genderFrequency,
            aes(x=gender,
                y=count))
plot1=base + geom_bar(stat='identity') + scale_y_continuous(breaks = c(175, 20000, 30000, 40000, 45000), limits = c(0, 50000))

plot2=plot1 + geom_text(position = position_dodge(0.9),
                               angle=360,
                               hjust=1,
                               vjust=-1,
                               aes(label=count))

TitleLayer = list(Title = "Gender Demographics of High School Seniors in WA State",
                   SubTi = NULL,
                   XTi = "Gender",
                   YTi = "Count",
                   Sou = "Source: OSPI Report Card Enrollment 2019-2020 School Year")

plot3=plot2+ labs(title = TitleLayer$Title,
                    subtitle = TitleLayer$SubTi,
                    x = TitleLayer$XTi,
                    y = TitleLayer$YTi,
                    caption = TitleLayer$Sou)
plot3
```






### Bivariate Plot

```{r}
Top5Counties <- schools[schools$County=="King"|schools$County== "Pierce"|schools$County=="Snohomish"|schools$County=="Spokane"|schools$County=="Clark",]

library(ggplot2)
base=ggplot(data=Top5Counties,
            aes(x=County,y=Homeless))

plot2=base + geom_boxplot()

TitleLayer = list(Title = "Homesless Students in the 12th Grade",
                   SubTi = "in the Top 5 Most Populous Counties in WA",
                   XTi = "County",
                   YTi = "Homeless Counts by School District",
                   Sou = "Source: OSPI Report Card Enrollment 2019-2020 School Year")

plot3=plot2+ labs(title = TitleLayer$Title,
                    subtitle = TitleLayer$SubTi,
                    x = TitleLayer$XTi,
                    y = TitleLayer$YTi,
                    caption = TitleLayer$Sou)
plot3 + coord_flip()

```


Row
-----------------------------------------------------------------------

### Washington Map

```{r}
location="https://github.com/G7-PUBPOL-543/wa-school-data/raw/main/waschools_homelessratio.csv"
schools=read.csv(location)
```

```{r}
library(sf)
linkMap="https://github.com/G7-PUBPOL-543/.JSON-Maps/raw/main/Washington_Counties_with_Natural_Shoreline___washsh_area.json"
```

```{r}
WAcountymap=read_sf(linkMap)

schools$COUNTYLABE
schools$COUNTYLABE <- (schools$County)

WAcountymapVars=merge(WAcountymap, 
                   schools, 
                   by='COUNTYLABE') 

library(ggplot2)
base = ggplot(data=WAcountymap) + 
  
        geom_sf(fill='grey90',color=NA) + theme_classic() +
        
              labs(x= "Longitude", y = "Latitude", fill="")

colMap= base + geom_sf(data=WAcountymapVars,
                       aes(fill="HL.Ratio"),
                       color=NA)
#I CANNOT figure out why it isn't recognizing individual values per county; why is it filling the entire state as the same??

TitleLayer = list(Title = "Average 12th Grade Student Homelessness",
                   SubTi = "by County in WA State",
                   XTi = NULL,
                   YTi = NULL,
                   Sou = "Source: OSPI Report Card Enrollment 2019-2020 School Year")

FinalMap=colMap + labs(title = TitleLayer$Title,
                    subtitle = TitleLayer$SubTi,
                    x = TitleLayer$XTi,
                    y = TitleLayer$YTi,
                    caption = TitleLayer$Sou)
FinalMap
```

